// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFGQb7sy-jSMCq-RZOABWCONw1JMsPHfo',
    appId: '1:858186433914:web:b805c809a99db56609c2c3',
    messagingSenderId: '858186433914',
    projectId: 'lockers-test',
    authDomain: 'lockers-test.firebaseapp.com',
    databaseURL: 'https://lockers-test-default-rtdb.firebaseio.com',
    storageBucket: 'lockers-test.firebasestorage.app',
    measurementId: 'G-WDE5BZPTTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMstBlMGJdSS2XQBlhfuPmb84G3io0mwo',
    appId: '1:858186433914:android:8fd30b3a4816196609c2c3',
    messagingSenderId: '858186433914',
    projectId: 'lockers-test',
    databaseURL: 'https://lockers-test-default-rtdb.firebaseio.com',
    storageBucket: 'lockers-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHrvWTbLI32GowNEUWxs7vjooAdHFlwA',
    appId: '1:858186433914:ios:d26843ee7e725ab909c2c3',
    messagingSenderId: '858186433914',
    projectId: 'lockers-test',
    databaseURL: 'https://lockers-test-default-rtdb.firebaseio.com',
    storageBucket: 'lockers-test.firebasestorage.app',
    iosBundleId: 'com.example.smartLockerApp',
  );
}
